/**
 * THE POSE THAT STRAIGHTENS THE WORM — solved, not authored.
 *
 * The earthworm's bind pose is an S, which is fine to rig in and useless
 * to animate from: every motion the game gives it is measured against
 * straight, so straight has to exist first. These are the local rotations
 * that lay every bone's child-offset along the chain's own first segment.
 *
 * Generated by `npm run probe:worm -- --write`. Solved rather than typed,
 * so a re-export of the model regenerates rather than being hand-nudged:
 * it took the joints from a mean bend of 28.1° to
 * 0°, and the chain to a straightness of
 * 1 where 1 is a line.
 *
 * The axis is the ROOT'S FIRST SEGMENT, not head-to-tail. On an S those
 * are wildly different — the ends can point back at each other — so
 * straightening onto head-to-tail would swing the whole animal instead of
 * unbending it. This way the head stays put and the body lines up behind.
 */
export interface BonePose {
  readonly bone: string;
  /** Local rotation, as a quaternion: x, y, z, w. */
  readonly quat: readonly [number, number, number, number];
}

export const WORM_STRAIGHT: readonly BonePose[] = [
  { bone: 'Bone_000', quat: [-0.51253, 0, -0.429095, 0.743768] },
  { bone: 'Bone_016', quat: [0, 0, 0, 1] },
  { bone: 'Bone_015', quat: [0, 0, 0, 1] },
  { bone: 'Bone_014', quat: [0, 0, 0, 1] },
  { bone: 'Bone_013', quat: [0, 0, 0, 1] },
  { bone: 'Bone_012', quat: [0, 0, 0, 1] },
  { bone: 'Bone_011', quat: [0, 0, 0, 1] },
  { bone: 'Bone_010', quat: [0, 0, 0, 1] },
  { bone: 'Bone_009', quat: [0, 0, 0, 1] },
  { bone: 'Bone_008', quat: [0, 0, 0, 1] },
  { bone: 'Bone_007', quat: [0, 0, 0, 1] },
  { bone: 'Bone_006', quat: [0, 0, 0, 1] },
  { bone: 'Bone_005', quat: [0, 0, 0, 1] },
  { bone: 'Bone_004', quat: [0, 0, 0, 1] },
  { bone: 'Bone_003', quat: [0, 0, 0, 1] },
  { bone: 'Bone_002', quat: [0, 0, 0, 1] },
];
